[package]
name = "stack-assembly"
version = "0.1.0"
edition = "2024"
description = "minimalist, stack-based, assembly-like programming language"
license = "0BSD"
repository = "https://github.com/hannobraun/stack-assembly"

[dependencies.bytemuck]
version = "1.24.0"
features = ["derive"]
